## IMPORT THE RELEVANT LIBRARIES

In [1]:
import pandas as pd
import numpy as np

## LOAD THE DATA

In [2]:
#Here we load the preprocessed data set that we made from the previous preprocessing work.
data_preprocessed = pd.read_csv('preprocessed.csv')

In [3]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

## CREATE THE TARGETS

In [4]:
#We try to find the median from 'Absenteeism Time in Hours'and take it as a cutoff line.
#Values below median is normal and above it is excessive.
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
#Everyone absent below the value 3 are assigned '0' and above 3 are assigned '1'.
#Since these are the values we are aiming for, they are known as 'targets'.
# Our task is to obtain a '0' or '1'.
# We create a new variable called'targets'.
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 3, 1, 0)

In [6]:
targets
#Targets is an np array which contains only 1s and 0s.

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
#We make the targets as the data_preprocessed['Execcive Absenteeism']
data_preprocessed['Exesseive Absenteeism'] = targets

In [8]:
# We map the data.
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Exesseive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

## A COMMENT ON TARGETS

In [9]:
# We find the total number of targets that are 0s and 1s respectively. 
# We divide the number of targets that are '1' by total number of targets.
targets.sum() / targets.shape[0]
# Around 46% of the targets are 1s and 54% are 0s.

0.45571428571428574

In [10]:
# We drop the 'Absenteeism Time in Hours' since we wo'nt need it anymore. data_with_targets is our new variable.
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'], axis = 1)

In [11]:
# To see whether data_with_targets represent the same information as data_preprocessed  we use 'is'.
# There are two possible results 'T' or 'F'.
data_with_targets is data_preprocessed

False

In [12]:
data_with_targets.head()
# data_with_targets is our checkpoint then.                      

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Exesseive Absenteeism  
0               30          0         2     1                      1  
1               31          0         1     0                      0  
2               31          0         0     0                      0  
3               24          0         2     0                      1  
4               30          0         2     1                      0

## SELECT THE INPUTS FOR REGRESSION

In [13]:
# To find the shape of our targets.
data_with_targets.shape

(700, 15)

In [14]:
# To select the inputs for regression we select all rows and all colums except"Excessive Absenteeism'.
data_with_targets.iloc[:,0:14]
# Iloc excludes the ending index'Excessive Absenteeism'.

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  
0                 30          0         2     1  
1                 31          0         1     0  
2                 31          0         0     0  
3                 24          0         2     0  
4                 30          0         2     1  
..               ...        ...       ...   ...  
695               22          1         2     0  
696               24          0         1     2  
697               25          1         0     0  
698               25          1         0     0  
699               25          0         1     1  

[700 rows x 14 columns]

In [15]:
data_with_targets.iloc[:,:-1]
# It gives exactly the same result as before.

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  
0                 30          0         2     1  
1                 31          0         1     0  
2                 31          0         0     0  
3                 24          0         2     0  
4                 30          0         2     1  
..               ...        ...       ...   ...  
695               22          1         2     0  
696               24          0         1     2  
697               25          1         0     0  
698               25          1         0     0  
699               25          0         1     1  

[700 rows x 14 columns]

In [16]:
# Let's create a variable unscaled_inputs with all information from data_with_tragets.
unscaled_inputs =data_with_targets.iloc[:,:-1]

## STANDARDIZE THE DATA

In [17]:
from sklearn.preprocessing import StandardScaler

absenteeism_scaler = StandardScaler()

In [18]:
# This is a custom scaler based on standard scaler from sklearn.
# Custom scaler will not standardize all inputs but only the ones we choose.In this way we preserve the dummies untouched.
# We choose the columns to be scaled.
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler = StandardScaler(copy,with_mean,with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None

    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self

    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [19]:
# We check the column values of the unscaled inputs.
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [20]:
#columns_to_scale = ['Month Value','Day of the Week', 'Transportation Expense', 'Distance to Work',
       #'Age', 'Daily Work Load Average', 'Body Mass Index', 'Children', 'Pet']
# We omit the dummy variables from the list.
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

In [21]:
# We create a new variable called columns_to_scale that contains the features to be scaled.
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [22]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [23]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Month Value', 'Day of the Week',
                      'Transportation Expense', 'Distance to Work', 'Age',
                      'Daily Work Load Average', 'Body Mass Index', 'Children',
                      'Pets'],
             copy=None, with_mean=None, with_std=None)

In [24]:
# We create a new variable called scaled_inputs that contains the features of transformed unscaled inputs.
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [25]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1     0.182726        -0.683704   
1           0         0         0         0     0.182726        -0.683704   
2           0         0         0         1     0.182726        -0.007725   
3           1         0         0         0     0.182726         0.668253   
4           0         0         0         1     0.182726         0.668253   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0    -0.388293        -0.007725   
696         1         0         0         0    -0.388293        -0.007725   
697         1         0         0         0    -0.388293         0.668253   
698         0         0         0         1    -0.388293         0.668253   
699         0         0         0         1    -0.388293         0.668253   

     Transportation Expense  Distance to Work       Age  \
0                  1.005844          0.412816 -0.536062   
1                 -1.574681         -1.141882  2.130803   
2                 -0.654143          1.426749  0.248310   
3                  0.854936         -1.682647  0.405184   
4                  1.005844          0.412816 -0.536062   
..                      ...               ...       ...   
695               -0.654143         -0.533522  0.562059   
696                0.040034         -0.263140 -1.320435   
697                1.624567         -0.939096 -1.320435   
698                0.190942         -0.939096 -0.692937   
699                1.036026          0.074838  0.562059   

     Daily Work Load Average  Body Mass Index  Education  Children      Pets  
0                  -0.806331         0.767431          0  0.880469  0.268487  
1                  -0.806331         1.002633          0 -0.019280 -0.589690  
2                  -0.806331         1.002633          0 -0.919030 -0.589690  
3                  -0.806331        -0.643782          0  0.880469 -0.589690  
4                  -0.806331         0.767431          0  0.880469  0.268487  
..                       ...              ...        ...       ...       ...  
695                -0.853789        -1.114186          1  0.880469 -0.589690  
696                -0.853789        -0.643782          0 -0.019280  1.126663  
697                -0.853789        -0.408580          1 -0.919030 -0.589690  
698                -0.853789        -0.408580          1 -0.919030 -0.589690  
699                -0.853789        -0.408580          0 -0.019280  0.268487  

[700 rows x 14 columns]

In [26]:
# from sklearn.preprocessing import StandardScaler
# #Let's assign a new variable for that ie, 'Absenteeism_scaler'.
# #We created an empty object with no information.
# absenteeism_scaler  = StandardScaler()

In [27]:
scaled_inputs.shape

(700, 14)

In [28]:
# # absenteeism_scaler will be used to subtract the mean and divide by the standar deviation featurewise and variablewise.
# # We fit our input data.
# absenteeism_scaler.fit(unscaled_inputs)

In [29]:
# # We have just prepared the scaling mechanism. we just have to trandform it now creating a new variable 'scaled_inputs'.
# scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [30]:
# scaled_inputs show us that all input data has been standardised.
# scaled_inputs

In [31]:
# Shape of scaled_inputs show we have 700 observations with 14 features.
# scaled_inputs.shape

## SPLIT THE DATA INTO TRAIN AND TEST AND SHUFFLE

## IMPORT THE RELEVANT MODULE

In [32]:
from sklearn.model_selection import train_test_split
# It splits the arrays and matrices into test and train subsets.

## SPLIT

In [33]:
# Our inputs are contained into 'scaled_inputs' and our targets are contained into 'targets'.
# It gives a training dataset with inputs and targets and a test dataset with inputs and targets with 4 arrays.
# If we rerun our code we get a different split and shuffle each time. It can can higher as well as lower accuracy with shuffling.
train_test_split(unscaled_inputs, targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
 302         0         0         0         1           10                6   
 262         0         0         0         1            8                2   
 489         0         0         0         1            8                3   
 297         0         0         0         1           10                2   
 65          0         0         0         1           10                3   
 ..        ...       ...       ...       ...          ...              ...   
 150         0         0         0         1            2                3   
 189         0         0         0         1            4                4   
 406         0         0         0         0            3                3   
 379         0         0         0         1            2                4   
 289         0         0         0         1           10                2   
 
      Transportation Expense  Distance to Work  Age  Daily Wor

In [34]:
# Lets declare four variables that contains 4 outputs.
# Train size takes values between 0 and 1.
# We choose train_size = 0.8. Then test_size  = 0.2
# Random state splits arrays and matrices into randow train and test subsets. it shuffles in same random way.
x_train, x_test, y_train, y_test = train_test_split(unscaled_inputs, targets, train_size = 0.8, random_state = 20)

In [35]:
# To check the shape of each of the four variables.
# This shows input contains 525 observations with 14 features with atrget variable 525.
# Therefore after setting test_size and random-state our 80-20 split worked as it should. 
# New values are 560 inputs with 14 features giving a train of 80% and test of 20%.
print (x_train.shape, y_train.shape)

(560, 14) (560,)


In [36]:
# This shows the inputs have 175 observations with 14 features with target variable 175.
# This shows traing helps 755 and testing helps with 25%.
print ( x_test.shape, y_test.shape)

(140, 14) (140,)


## LOGISTIC REGRESSION WITH SKLEARN

In [37]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

## TRAINING THE MODEL

In [38]:
# Lets create a new variable with logistic regression object.
reg   = LogisticRegression()

In [39]:
# Each of the parameters have meaning that can improver our model onw way or the other.
reg.fit(x_train, y_train)

C:\Users\Amit Bose\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [40]:
# The score method gives the mean accuracy on the given test data and labels.
# This shows our model has accuracy of 0.8 or 80%.
reg.score(x_train, y_train)

0.7571428571428571

## MANUALLY CHECK THE ACCURACY


In [41]:
# Accuracy means 80% of the model outputs meets target. We shoul manually compare outputs with target.
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [42]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [43]:
# Its quite difficult to compre there we use the boolean way of checking to compare elecments of the two variables.
# If there is a match the result is true otherwise it is false.
model_outputs  == y_train


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [44]:
# To find how many are true and false and 424 are true entries.
np.sum((model_outputs  == y_train))

424

In [45]:
# To find the shape of the model_outputs.
model_outputs.shape

(560,)

In [46]:
# Accuracy is coorect predictions / observations and get exact result as reg.score.
np.sum(np.sum((model_outputs  == y_train)) / model_outputs.shape)

0.7571428571428571

## FINDING THE INTERCEPT AND COEFFICIENT

In [47]:
reg.intercept_

array([-1.72486003])

In [48]:
reg.coef_

array([[ 2.53932449,  0.78093105,  2.86125336,  0.55034704,  0.03253833,
        -0.06259039,  0.00806166, -0.00375149, -0.04114049, -0.00377576,
         0.03819794, -0.45993978,  0.31508328, -0.25173633]])

In [49]:
# We want to know what variable these coefficients refer to.
# To get the column values from unscaled_inputs
unscaled_inputs.columns.values


array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [50]:
# A new variable called feature_name contains all information about colums.values.
feature_name = unscaled_inputs.columns.values

In [51]:
# We now create a summary table containing feature name information.
summary_table  = pd.DataFrame(columns = ['Feature_name'], data = feature_name)
# To create a new column called coefficient
summary_table ['Coefficient'] = np.transpose(reg.coef_)

In [52]:
summary_table

Feature_name  Coefficient
0                  Reason_1     2.539324
1                  Reason_2     0.780931
2                  Reason_3     2.861253
3                  Reason_4     0.550347
4               Month Value     0.032538
5           Day of the Week    -0.062590
6    Transportation Expense     0.008062
7          Distance to Work    -0.003751
8                       Age    -0.041140
9   Daily Work Load Average    -0.003776
10          Body Mass Index     0.038198
11                Education    -0.459940
12                 Children     0.315083
13                     Pets    -0.251736

In [53]:
# To add the intercept
# To shift up all indices by 1
summary_table.index = summary_table.index+1

In [54]:
# Now the 0th row is empty. We fill it with the intercept.
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]

In [55]:
summary_table = summary_table.sort_index()
summary_table

Feature_name  Coefficient
0                 Intercept    -1.724860
1                  Reason_1     2.539324
2                  Reason_2     0.780931
3                  Reason_3     2.861253
4                  Reason_4     0.550347
5               Month Value     0.032538
6           Day of the Week    -0.062590
7    Transportation Expense     0.008062
8          Distance to Work    -0.003751
9                       Age    -0.041140
10  Daily Work Load Average    -0.003776
11          Body Mass Index     0.038198
12                Education    -0.459940
13                 Children     0.315083
14                     Pets    -0.251736

## INTERPRETING THE COEFFICIENTS

In [56]:
# Standerdized coefficients are coefficients of regression where all variables are standardised.
# Odds ratio are what we get after we get exponentials of the coefficients.
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [57]:
summary_table


Feature_name  Coefficient  Odds_ratio
0                 Intercept    -1.724860    0.178198
1                  Reason_1     2.539324   12.671109
2                  Reason_2     0.780931    2.183504
3                  Reason_3     2.861253   17.483426
4                  Reason_4     0.550347    1.733855
5               Month Value     0.032538    1.033073
6           Day of the Week    -0.062590    0.939328
7    Transportation Expense     0.008062    1.008094
8          Distance to Work    -0.003751    0.996256
9                       Age    -0.041140    0.959694
10  Daily Work Load Average    -0.003776    0.996231
11          Body Mass Index     0.038198    1.038937
12                Education    -0.459940    0.631322
13                 Children     0.315083    1.370373
14                     Pets    -0.251736    0.777450

In [58]:
# Sort_values sort values in dataframe with respect to given column.
summary_table .sort_values('Odds_ratio',ascending = False)

Feature_name  Coefficient  Odds_ratio
3                  Reason_3     2.861253   17.483426
1                  Reason_1     2.539324   12.671109
2                  Reason_2     0.780931    2.183504
4                  Reason_4     0.550347    1.733855
13                 Children     0.315083    1.370373
11          Body Mass Index     0.038198    1.038937
5               Month Value     0.032538    1.033073
7    Transportation Expense     0.008062    1.008094
8          Distance to Work    -0.003751    0.996256
10  Daily Work Load Average    -0.003776    0.996231
9                       Age    -0.041140    0.959694
6           Day of the Week    -0.062590    0.939328
14                     Pets    -0.251736    0.777450
12                Education    -0.459940    0.631322
0                 Intercept    -1.724860    0.178198

## TESTING THE MODEL

In [59]:
# The further away from 0 the coefficient is, the bigger is its importance.
reg.score(x_test,y_test)

0.7285714285714285

In [60]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.7699994 , 0.2300006 ],
       [0.65488913, 0.34511087],
       [0.51799236, 0.48200764],
       [0.78477447, 0.21522553],
       [0.06273661, 0.93726339],
       [0.2797647 , 0.7202353 ],
       [0.25183873, 0.74816127],
       [0.14379678, 0.85620322],
       [0.7689083 , 0.2310917 ],
       [0.75099303, 0.24900697],
       [0.5074636 , 0.4925364 ],
       [0.16973467, 0.83026533],
       [0.08707647, 0.91292353],
       [0.72261541, 0.27738459],
       [0.29672096, 0.70327904],
       [0.56347418, 0.43652582],
       [0.533486  , 0.466514  ],
       [0.6878374 , 0.3121626 ],
       [0.34780446, 0.65219554],
       [0.04765696, 0.95234304],
       [0.6911915 , 0.3088085 ],
       [0.77401446, 0.22598554],
       [0.36330265, 0.63669735],
       [0.39272374, 0.60727626],
       [0.19129571, 0.80870429],
       [0.78580646, 0.21419354],
       [0.45788814, 0.54211186],
       [0.85109978, 0.14890022],
       [0.21579024, 0.78420976],
       [0.76287905, 0.23712095],
       [0.

In [61]:
predicted_proba.shape

(140, 2)

In [62]:
predicted_proba[:,1]

array([0.2300006 , 0.34511087, 0.48200764, 0.21522553, 0.93726339,
       0.7202353 , 0.74816127, 0.85620322, 0.2310917 , 0.24900697,
       0.4925364 , 0.83026533, 0.91292353, 0.27738459, 0.70327904,
       0.43652582, 0.466514  , 0.3121626 , 0.65219554, 0.95234304,
       0.3088085 , 0.22598554, 0.63669735, 0.60727626, 0.80870429,
       0.21419354, 0.54211186, 0.14890022, 0.78420976, 0.23712095,
       0.39364598, 0.69977148, 0.58819271, 0.50242113, 0.22598554,
       0.46486091, 0.26851174, 0.79117882, 0.40717761, 0.61412384,
       0.22536534, 0.46319533, 0.22538365, 0.46055957, 0.70724828,
       0.67035172, 0.7922954 , 0.21610015, 0.23706598, 0.15398924,
       0.61305043, 0.3638799 , 0.60490772, 0.29913651, 0.8578902 ,
       0.42881143, 0.90869294, 0.32820836, 0.28625244, 0.302915  ,
       0.74890916, 0.66634907, 0.36779018, 0.84357391, 0.21402547,
       0.25997552, 0.14477078, 0.26468602, 0.78027232, 0.30808858,
       0.24104954, 0.23387703, 0.88754474, 0.3664    , 0.60862

## SAVE THE MODEL

In [63]:
import pickle

In [64]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [65]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)